---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "External"
subtitle: "Digital Start"
#logo: "logo.png"
icon: "fas fa-external-link-alt" # Optional icon

header: true
footer: false
#footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional navbar
#links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
# - name: "Contribute"
#   icon: "fab fa-github"
#   url: "https://github.com/bastienwirtz/homer"
#   target: "_blank" # optional html a tag target attribute
# - name: "Wiki"
#   icon: "fas fa-book"
#   url: "https://www.wikipedia.org/"
 # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
 # see url field and assets/additionnal-page.yml.dist used in this example:
 - name: "Internal Start (mDNS)"
   icon: "fas fa-network-wired"
   url: "http://nas.local:8080" 
 - name: "Internal Start (Fritz)"
   icon: "fas fa-network-wired"
   url: "http://nas.fritz.box:8080" 


# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Fast Access"
    icon: "fas fa-server"
    items:
      - name: "GMail"
        icon: "fas fa-at"
        url: "https://mail.google.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Maps"
        icon: "fas fa-map-marked-alt"
        url: "https://maps.google.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Amazon"
        icon: "fab fa-amazon"
        url: "http://amazon.co.uk/"
        target: "_blank" # optional html a tag target attribute
  - name: "Train"
    icon: "fas fa-train"
    items:
      - name: "RTT"
        subtitle: "Real Time Trains"
        icon: "fas fa-train"
        url: "http://realtimetrains.co.uk/"
        target: "_blank" # optional html a tag target attribute
      - name: "RTT - PWE to GLC"
        subtitle: "Pollokshaws East to Glasgow Central"
        icon: "fas fa-arrow-right"
        url: "https://www.realtimetrains.co.uk/search/detailed/gb-nr:PWE/to/gb-nr:GLC?stp=WVS&show=all&order=wtt"
        target: "_blank" # optional html a tag target attribute
      - name: "RTT - GLC to PWD"
        subtitle: "Glasgow Central to Pollokshaws East"
        icon: "fas fa-arrow-left"
        url: "https://www.realtimetrains.co.uk/search/detailed/gb-nr:GLC/to/gb-nr:PWE?stp=WVS&show=all&order=wtt"
        target: "_blank" # optional html a tag target attribute
  - name: "Other"
    icon: "fas fa-icons"
    items:      
      - name: "My Workspace"
        icon: "fas fa-university"
        url: "http://myworkspace.jpmchase.com"
        subtitle: "JPMC Citrix Remote Access"
