---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "External"
subtitle: "Digital Start"
#logo: "logo.png"
icon: "fas fa-external-link-alt" # Optional icon

header: true
footer: false
#footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional navbar
#links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
# - name: "Contribute"
#   icon: "fab fa-github"
#   url: "https://github.com/bastienwirtz/homer"
#   target: "_blank" # optional html a tag target attribute
# - name: "Wiki"
#   icon: "fas fa-book"
#   url: "https://www.wikipedia.org/"
 # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
 # see url field and assets/additionnal-page.yml.dist used in this example:
 - name: "Internal Start (mDNS)"
   icon: "fas fa-network-wired"
   url: "http://nas.local:8080" 
 - name: "Internal Start (Fritz)"
   icon: "fas fa-network-wired"
   url: "http://nas.fritz.box:8080" 


# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Fast Access"
    icon: "fas fa-server"
    items:
      - name: "GMail"
#        icon: "fas fa-at"
        logo: "assets/tools/google-mail.png"
        url: "https://mail.google.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Maps"
#        icon: "fas fa-map-marked-alt"
        logo: "assets/tools/googlemaps.png"
        url: "https://maps.google.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Amazon"
#        icon: "fab fa-amazon"
        logo: "assets/tools/amazon.png"
        url: "http://amazon.co.uk/"
        target: "_blank" # optional html a tag target attribute
  - name: "Train"
    icon: "fas fa-train"
    items:
      - name: "RTT"
        subtitle: "Real Time Trains"
#        icon: "fas fa-train"
        logo: "assets/tools/rtt.png"
        url: "http://realtimetrains.co.uk/"
      - name: "RTT - PWE to GLC"
        subtitle: "Pollokshaws East to Glasgow Central"
        icon: "fas fa-arrow-right"
        url: "https://www.realtimetrains.co.uk/search/detailed/gb-nr:PWE/to/gb-nr:GLC?stp=WVS&show=all&order=wtt"
      - name: "RTT - GLC to PWE"
        subtitle: "Glasgow Central to Pollokshaws East"
        icon: "fas fa-arrow-left"
        url: "https://www.realtimetrains.co.uk/search/detailed/gb-nr:GLC/to/gb-nr:PWE?stp=WVS&show=all&order=wtt"
  - name: "Work"
    icon: "fas fa-university"
    items:      
      - name: "My Workspace"
        icon: "fas fa-laptop-house"
        url: "http://myworkspace.jpmchase.com"
        subtitle: "JPMC Citrix Remote Access"
        target: "_blank" # optional html a tag target attribute
#      - name: "Daily Health Check"
#        icon: "fas fa-shield-virus"
#        url: "https://jpmc.co1.qualtrics.com/jfe/form/SV_9M0Lr3A4z1xY7B3?Q_TS_ID=TS_37yhpLreARsWqWx&Q_TS_RS=Self&Q_EE_ANON=1&_=1"
#        target: "_blank" # optional html a tag target attribute
  - name: "Other"
    icon: "fas fa-icons"
    items:      
      - name: "Wikipedia"
        icon: "fab fa-wikipedia-w"
        url: "http://en.wikipedia.org/"
        target: "_blank" # optional html a tag target attribute
      - name: "Todoist"
        logo: "assets/tools/todoist.png"
        url: "https://todoist.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "DuckDuckGo"
        logo: "assets/tools/duckduckgo.png"
        url: "https://duckduckgo.com"
        target: "_blank" # optional html a tag target attribute
  - name: "Climbing"
    icon: "fas fa-mountain"
    items:      
      - name: "TCA Life"
        icon: "fas fa-newspaper"
        url: "https://www.theclimbingacademy.com/tca-life/"
        target: "_blank" # optional html a tag target attribute
      - name: "TCA Current Occupation"
        icon: "fas fa-tachometer-alt"
        url: "https://portal.rockgympro.com/portal/public/d0f355e237dda999f3112d94d3c762c7/occupancy?&iframeid=occupancyCounter&fId="
        target: "_blank" # optional html a tag target attribute
      - name: "TCA Capacity Tracker"
        icon: "fas fa-chart-area"
        url: "https://tcatracker.nw.r.appspot.com/"
        target: "_blank" # optional html a tag target attribute

