# Publish pre-build release
name: Create Github release

on:
  push:
    tags: [v*]

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: pnpm setup
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - 
        name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - 
        name: Build project
        run: |
          pnpm install --frozen-lockfile
          pnpm build
      - 
        name: Create artifact
        working-directory: "dist"
        run: zip -r ../homer.zip ./*
      - 
        name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            homer.zip